### ISSUE TITLE
Please add zopflipng to this tool!

### ISSUE THREAD

**Issue by Petoj87** [macik/Image_catalyst#2]
Please add zopflipng to this tool!

**Comment by macik** [comment]
1. I'm not the author of this project and only maintain GitHub upload for personal use
2. This tool used several PNG utilities to reach highest level of tatal PNG compression
3. Do you have actual tests for  zopflipng vs ImgCatalyst 2.4 ?

**Comment by Petoj87** [comment]
I tried to download 2.4 but i get the error "Access to the file is restricted".
Also if i download the sources and try to run them i get some russian error that 
jpegstripper, jpginfo, mozjpgtran are missing!

**Comment by macik** [comment]
I'm updated repo to version 2.4 and add English version of *.bat file. So try it.

**Comment by Petoj87** [comment]
Now i get the error in English but the files jpegstripper, jpginfo, mozjpgtran are still missing.

**Comment by macik** [comment]
Oh, ok.  I get it.
These files had been excluded from upload by .gitignore or somewhat, so missed this moment as they exists in local repo.

Uploaded it to repo. Please test it.

**Comment by macik** [comment]
Moreover I send info about `zopflipng` to author of ImageCatalyst. He said that it would be inspected.

**Comment by Petoj87** [comment]
Why on earth does this tool start a new PING.EXE every second?

**Comment by macik** [comment]
I'm not certain, but as I remember it's one of hack method to set defined timeout in Windows CMD.

**Comment by macik** [comment]
See new version in authors official repository:
https://github.com/lorents17/iCatalyst/

Now it utilizes `zopflipng` in extreme PNG mode.
